#Configuracion
#Tue May 12 15:41:00 PDT 2026
home.window.height=700
home.window.width=900
home.window.x=233
home.window.y=10
registration.window.height=700
registration.window.width=900
registration.window.x=233
registration.window.y=10
ui.theme=dark
