#Configuracion
#Tue May 19 09:48:01 MDT 2026
home.window.height=830
home.window.width=1550
home.window.x=-7
home.window.y=-7
registration.window.height=700
registration.window.width=900
registration.window.x=233
registration.window.y=10
ui.theme=dark
