#Configuracion
#Tue May 26 22:09:59 MDT 2026
home.window.height=575
home.window.width=925
home.window.x=226
home.window.y=102
registration.window.height=700
registration.window.width=900
registration.window.x=233
registration.window.y=10
ui.theme=light
